#서버 포트
server:
  port: 8080


spring:
  config:
    import: file:.env[.properties]
  application:
    name: gateway-service

  #클라우드
  cloud:
    gateway:
      routes:
#
#        - id: user-service-with-authentication
#          uri: lb://USER-SERVICE
#          predicates:
#            -
#          filters:
#            - RewritePath=/user-service/(?<remaining>.*), /${remaining}
#            - name: JwtAuthenticationFilter
#              args:
#                loginPageRedirectionUrl: "${LOGIN_URL}"
#            - name: RemoveUserHeadersFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<remaining>.*), /${remaining}

#        - id: auth-service-with-authentication
#          uri: lb://USER-SERVICE
#          predicates:
#            -
#          filters:
#            - name: JwtAuthenticationFilter
#              args:
#                loginPageRedirectionUrl: "${LOGIN_URL}"

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/(?<remaining>.*), /${remaining}





#유레카
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_URL}"


#JWT 토큰
jwt:
  secretKey: ${JWT_SECRET_KEY}
